version: 2.1
jobs:
  build: 
    working_directory: ~/SE-GROUP10
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      

  test:
    working_directory: ~/SE-GROUP10
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
